Traceback (most recent call last):
  File "/Users/helmut/Code/oe-python-template/.nox/docs-3-13/bin/oe-python-template", line 4, in <module>
    from oe_python_template.cli import cli
  File "/Users/helmut/Code/oe-python-template/src/oe_python_template/cli.py", line 13, in <module>
    from oe_python_template.api import api_v1, api_v2
  File "/Users/helmut/Code/oe-python-template/src/oe_python_template/api.py", line 16, in <module>
    from fastapi import Depends, FastAPI, Response, status
  File "/Users/helmut/Code/oe-python-template/.nox/docs-3-13/lib/python3.13/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/Users/helmut/Code/oe-python-template/.nox/docs-3-13/lib/python3.13/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/Users/helmut/Code/oe-python-template/.nox/docs-3-13/lib/python3.13/site-packages/fastapi/routing.py", line 24, in <module>
    from fastapi import params
  File "/Users/helmut/Code/oe-python-template/.nox/docs-3-13/lib/python3.13/site-packages/fastapi/params.py", line 5, in <module>
    from fastapi.openapi.models import Example
  File "/Users/helmut/Code/oe-python-template/.nox/docs-3-13/lib/python3.13/site-packages/fastapi/openapi/models.py", line 4, in <module>
    from fastapi._compat import (
    ...<6 lines>...
    )
  File "/Users/helmut/Code/oe-python-template/.nox/docs-3-13/lib/python3.13/site-packages/fastapi/_compat.py", line 21, in <module>
    from fastapi.exceptions import RequestErrorModel
  File "/Users/helmut/Code/oe-python-template/.nox/docs-3-13/lib/python3.13/site-packages/fastapi/exceptions.py", line 139, in <module>
    RequestErrorModel: Type[BaseModel] = create_model("Request")
                                         ~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/helmut/Code/oe-python-template/.nox/docs-3-13/lib/python3.13/site-packages/pydantic/main.py", line 1678, in create_model
    return meta(
        model_name,
    ...<4 lines>...
        **kwds,
    )
  File "/Users/helmut/Code/oe-python-template/.nox/docs-3-13/lib/python3.13/site-packages/pydantic/_internal/_model_construction.py", line 224, in __new__
    complete_model_class(
    ~~~~~~~~~~~~~~~~~~~~^
        cls,
        ^^^^
    ...<4 lines>...
        create_model_module=_create_model_module,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/helmut/Code/oe-python-template/.nox/docs-3-13/lib/python3.13/site-packages/pydantic/_internal/_model_construction.py", line 620, in complete_model_class
    cls.__pydantic_validator__ = create_schema_validator(
                                 ~~~~~~~~~~~~~~~~~~~~~~~^
        schema,
        ^^^^^^^
    ...<5 lines>...
        config_wrapper.plugin_settings,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/helmut/Code/oe-python-template/.nox/docs-3-13/lib/python3.13/site-packages/pydantic/plugin/_schema_validator.py", line 38, in create_schema_validator
    plugins = get_plugins()
  File "/Users/helmut/Code/oe-python-template/.nox/docs-3-13/lib/python3.13/site-packages/pydantic/plugin/_loader.py", line 39, in get_plugins
    for entry_point in dist.entry_points:
                       ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/metadata/__init__.py", line 496, in entry_points
    return EntryPoints._from_text_for(self.read_text('entry_points.txt'), self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/metadata/__init__.py", line 294, in _from_text_for
    @classmethod
    
KeyboardInterrupt
